config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :descriptions
    resources :images
    resources :projects do
      member do
        get :edit_multiple_images
        put :update_multiple_images
        get :edit_multiple_descriptions
        put :update_multiple_descriptions
      end
    end
  end

  devise_for :users

  resources :images
  resources :projects, path: ''

end

app/models/admin/project.rb
class Admin::Project < Project

  geocoded_by :address
  after_validation :geocode

  def update_assets(arr, type)
    current_assets_ids = current_assets(type).map(&:asset_id)
    add_assets(arr - current_assets_ids, type)
    assets_to_delete = self.assets.where(asset_type: type).where.not(asset_id: arr)
    assets_to_delete.destroy_all
  end

  def current_assets(type)
    self.assets.where(asset_type: type)
  end

  def add_assets(arr, type)
    arr.each do |id|
      self.assets.create(project_id: self, asset_id: id, asset_type: type)
    end
  end

end

app/models/project.rb
class Project < ActiveRecord::Base

  validates :title, :title, :permalink, presence: true

  before_validation :set_permalink

  has_many :assets
  has_many :descriptions, -> { where assets: { asset_type: 'description' } },
            through: :assets
  has_many :images, -> { where assets: { asset_type: 'image' } },
            through: :assets
  
  belongs_to :parent, class_name: "Project", foreign_key: "project_id"
  has_many :children, class_name: "Project", foreign_key: "project_id"
  
  scope :published, -> { where(published: true) }
  scope :parents_only, -> { where(project_id: nil) }

  def image
    images.where(assets: {main: true}).take
  end

  def random_images
    images.where(assets: {main: false}).shuffle
  end

  def description
    images.where(assets: {main: true}).take
  end

  def to_param
    permalink
  end

  def set_permalink
    self.permalink = title.parameterize
  end

end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < AdminController
  before_action :set_admin_project, only: [:show, :edit, :update, :destroy, :edit_multiple_images, :update_multiple_images, :edit_multiple_descriptions, :update_multiple_descriptions]

  # GET /admin/projects
  # GET /admin/projects.json
  def index
    @admin_projects = Admin::Project.all
  end

  # GET /admin/projects/1
  # GET /admin/projects/1.json
  def show
  end

  # GET /admin/projects/new
  def new
    @admin_project = Admin::Project.new
  end

  # GET /admin/projects/1/edit
  def edit
  end

  # POST /admin/projects
  # POST /admin/projects.json
  def create
    @admin_project = Admin::Project.new(admin_project_params)

    respond_to do |format|
      if @admin_project.save
        format.html { redirect_to @admin_project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @admin_project }
      else
        format.html { render :new }
        format.json { render json: @admin_project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/projects/1
  # PATCH/PUT /admin/projects/1.json
  def update
    respond_to do |format|
      if @admin_project.update(admin_project_params)
        format.html { redirect_to @admin_project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_project }
      else
        format.html { render :edit }
        format.json { render json: @admin_project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/projects/1
  # DELETE /admin/projects/1.json
  def destroy
    @admin_project.destroy
    respond_to do |format|
      format.html { redirect_to admin_projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def edit_multiple_images
    @admin_images = Admin::Image.all
  end

  def update_multiple_images
    @admin_project.update_assets(admin_project_assets_params.map(&:to_i), 'image')
    redirect_to admin_project_path
  end

  def edit_multiple_descriptions
    @admin_descriptions = Admin::Description.all
  end

  def update_multiple_descriptions
    @admin_project.update_assets(admin_project_assets_params.map(&:to_i), 'description')
    redirect_to admin_project_path
  end

  def descriptions
    @available_descriptions = Admin::Project.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def set_admin_project
      @admin_project = Admin::Project.find_by_permalink(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_project_params
      params.require(:admin_project).permit(:title, :address, :permalink, :sequence, :published)
    end

    def admin_project_assets_params
      params.require(:project_assets)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :load_project, :load_hash_for_google_maps, only: :show

  def index
    redirect_to action: :show, id: 'recent-projects'
  end

  def show
    
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :permalink, :sequence)
    end

    def load_project
      @project = Project.find_by_permalink(params[:id])
    end

    def load_hash_for_google_maps
      if @project.children.present?
        @hash = Gmaps4rails.build_markers(@project.children) do |child, marker|
          marker.lat child.latitude
          marker.lng child.longitude
        end
      else
        @hash = Gmaps4rails.build_markers([@project]) do |project, marker|
          marker.lat project.latitude
          marker.lng project.longitude
        end
      end
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/admin/projects/_breadcrumb.html.erb
<ol class="breadcrumb">
  <li><%= link_to 'Projects', admin_projects_path %></a></li>
  <li class="active"><%= link_to @admin_project.title, @admin_project %></li>
</ol>

app/views/admin/projects/edit.html.erb
<%= render 'breadcrumb', object: @admin_project %>

<h1>Editing admin_project</h1>

<%= form_for @admin_project, html: { class: "form-horizontal", role: "form" } do |f| %>
  <% if @admin_project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_project.errors.count, "error") %> prohibited this admin_project from being saved:</h2>

      <ul>
      <% @admin_project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :title, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :address, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :address, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :permalink, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :permalink, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :sequence, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :sequence, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <div class="checkbox">
        <label>
          <%= f.check_box :published %>
          Published
        </label>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit 'Save', class: "btn btn-primary" %>
    </div>
  </div>
<% end %>


<%= link_to 'Show', @admin_project %> |
<%= link_to 'Back', admin_projects_path %>

app/views/admin/projects/edit_multiple_descriptions.html.erb
<%= render 'breadcrumb', object: @admin_project %>

<%= form_tag update_multiple_descriptions_admin_project_path, method: :put do %>
  <table class="table table-striped table-hover table-condensed">
    <thead>
      <tr>
        <th>#</th>
        <th>Linked?</th>
        <th>Name</th>
        <th>Text</th>
      </tr>
    </thead>

    <tbody>
      <% @admin_descriptions.each do |description| %>
        <%= fields_for "project_assets[]", description do |f| %>
          <tr>
            <td><%= description.id %></td>
            <td><%= check_box_tag "project_assets[]", description.id, @admin_project.descriptions.include?(description) %></td>
            <td><%= description.name %></td>
            <td><%= description.text %></td>
          </tr>
        <% end %>
      <% end %>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= submit_tag "Save", class: "btn btn-primary" %>
        </div>
      </div>
    </tbody>
  </table>
<% end %>

app/views/admin/projects/edit_multiple_images.html.erb
<%= render 'breadcrumb', object: @admin_project %>
<article class="row">
  <%= form_tag update_multiple_images_admin_project_path, method: :put, html: { class: "form-horizontal", role: "form" } do %>
    <% @admin_images.each do |image| %>
      <%= fields_for "project_assets[]", image do |f| %>
        <div class="col-xs-3 admin-block-image" style="background-image:url(<%= image.square_150x150 %>);">
          <div class="id-number">
            <label>
              #<%= image.id %>
              <%= check_box_tag "project_assets[]", image.id, @admin_project.images.include?(image) %>
            </label>
          </div>
          <div class="form-group">
            <%= f.label :name, class: "col-sm-2 control-label" %>
          </div>
          <div class="admin-file-name">
            <p><%= File.basename image.square_75x75 %></p>
          </div>
        </div>
      <% end %>
    <% end %>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= submit_tag "Save", class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</article>

app/views/admin/projects/index.html.erb
<h2>Projects</h2>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>#</th>
      <th>Title</th>
      <th>Permalink</th>
      <th>Sequence</th>
      <th>Published</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_projects.each do |adm_pr| %>
      <tr class=<%= "danger" unless adm_pr.published? %> >
        <td><%= adm_pr.id %></td>
        <td><%= link_to adm_pr.title, adm_pr %></td>
        <td><%= adm_pr.permalink %></td>
        <td><%= adm_pr.sequence %></td>
        <td><%= adm_pr.published %></td>
        <td><%= link_to 'Edit', edit_admin_project_path(adm_pr) %></td>
        <td><%= link_to 'Destroy', adm_pr, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_admin_project_path %>

app/views/admin/projects/new.html.erb
<h1>New admin_project</h1>

<%= form_for @admin_project, html: { class: "form-horizontal", role: "form" } do |f| %>
  <% if @admin_project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_project.errors.count, "error") %> prohibited this admin_project from being saved:</h2>

      <ul>
      <% @admin_project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :title, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :sequence, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :sequence, class: 'form-control' %>
    </div>
  </div>
    <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <div class="checkbox">
        <label>
          <%= f.check_box :parent %>
          Will have sub projects?
        </label>
      </div>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <div class="checkbox">
        <label>
          <%= f.check_box :published %>
          Published
        </label>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit 'Save', class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

<%= link_to 'Back', admin_projects_path %>

app/views/admin/projects/show.html.erb
<%= render 'breadcrumb', object: @admin_project %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @admin_project.title %>
</p>

<p>
  <strong>Address:</strong>
  <%= @admin_project.address %>
</p>

<p>
  <strong>latitude:</strong>
  <%= @admin_project.latitude %>
</p>
<p>
  <strong>longitude:</strong>
  <%= @admin_project.longitude %>
</p>

<p>
  <strong>Permalink:</strong>
  <%= @admin_project.permalink %>
</p>

<p>
  <strong>Sequence:</strong>
  <%= @admin_project.sequence %>
</p>

<p>
  <strong>Published:</strong>
  <%= @admin_project.published %>
</p>

<p>
  <strong>Should have subcategories:</strong>
  <%= @admin_project.parent %>
</p>

<div class="row">
  <div class="col-lg-12">
    <h3>Images</h3>
    <table class="table table-striped table-hover table-condensed">
      <thead>
        <tr>
          <th>#</th>
          <th>Preview</th>
          <th>Name</th>
        </tr>
      </thead>

      <tbody>
        <% @admin_project.images.each do |img| %>
          <tr>
            <td><%= link_to img.id, admin_image_path(img) %></td>
            <td><%= image_tag img.square_75x75 %></td>
            <td><%= img.name %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to 'Edit images', edit_multiple_images_admin_project_path, class: "btn btn-default btn-primary active", role: "button" %>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <h3>Descriptions</h3>
    <table class="table table-striped table-hover table-condensed">
      <thead>
        <tr>
          <th>#</th>
          <th>Name</th>
          <th>Text</th>
        </tr>
      </thead>

      <tbody>
        <% @admin_project.descriptions.each do |descr| %>
          <tr>
            <td><%= link_to descr.id, admin_description_path(descr) %></td>
            <td><%= descr.name %></td>
            <td><%= link_to descr.text, admin_description_path(descr) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to 'Edit descriptions', edit_multiple_descriptions_admin_project_path, class: "btn btn-default btn-primary active", role: "button" %>
  </div>
</div>

<%= link_to 'Edit', edit_admin_project_path(@admin_project) %> |
<%= link_to 'Back', admin_projects_path %>