config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :descriptions
    resources :images
    resources :projects do
      member do
        get :edit_multiple_images
        put :update_multiple_images
        get :edit_multiple_descriptions
        put :update_multiple_descriptions
      end
    end
  end

  devise_for :users

  resources :images
  resources :projects, path: ''

end

app/models/admin/description.rb
class Admin::Description < Description
end

app/models/description.rb
class Description < ActiveRecord::Base

  validates :text, presence: true

  has_many :assets
  has_many :projects, -> { where assets: { asset_type: 'description' } },
            through: :assets

end

app/controllers/admin/descriptions_controller.rb
class Admin::DescriptionsController < AdminController
  before_action :set_admin_description, only: [:show, :edit, :update, :destroy]

  # GET /admin/descriptions
  # GET /admin/descriptions.json
  def index
    @admin_descriptions = Admin::Description.all
  end

  # GET /admin/descriptions/1
  # GET /admin/descriptions/1.json
  def show
  end

  # GET /admin/descriptions/new
  def new
    @admin_description = Admin::Description.new
  end

  # GET /admin/descriptions/1/edit
  def edit
  end

  # POST /admin/descriptions
  # POST /admin/descriptions.json
  def create
    @admin_description = Admin::Description.new(admin_description_params)

    respond_to do |format|
      if @admin_description.save
        format.html { redirect_to @admin_description, notice: 'Description was successfully created.' }
        format.json { render :show, status: :created, location: @admin_description }
      else
        format.html { render :new }
        format.json { render json: @admin_description.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/descriptions/1
  # PATCH/PUT /admin/descriptions/1.json
  def update
    respond_to do |format|
      if @admin_description.update(admin_description_params)
        format.html { redirect_to @admin_description, notice: 'Description was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_description }
      else
        format.html { render :edit }
        format.json { render json: @admin_description.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/descriptions/1
  # DELETE /admin/descriptions/1.json
  def destroy
    @admin_description.destroy
    respond_to do |format|
      format.html { redirect_to admin_descriptions_url, notice: 'Description was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_description
      @admin_description = Admin::Description.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_description_params
      params.require(:admin_description).permit(:name, :text)
    end
end

app/views/admin/descriptions/edit.html.erb
<ol class="breadcrumb">
  <li><a href="#">Descriptions</a></li>
  <li class="active"><%= @admin_description.name %></li>
</ol>

<h1>Editing <%= @admin_description.name %></h1>

<%= form_for @admin_description, html: { class: "form-horizontal", role: "form" } do |f| %>
  <% if @admin_description.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_description.errors.count, "error") %> prohibited this admin_description from being saved:</h2>

      <ul>
      <% @admin_description.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :text, class: "col-sm-2 control-label"  %>
    <div class="col-sm-10">
      <%= f.text_area :text, class: 'form-control', rows: 25 %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit 'Save', class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

<%= link_to 'Show', @admin_description %> |
<%= link_to 'Preview', @admin_description %> |
<%= link_to 'Back', admin_descriptions_path %>

app/views/admin/descriptions/index.html.erb
<h2>Descriptions</h2>

<table class="table table-striped table-hover table-condensed">
  <thead>
    <tr>
      <th>#</th>
      <th>Name</th>
      <th>Text</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_descriptions.each do |admin_description| %>
      <tr>
        <td><%= admin_description.id %></td>
        <td><%= admin_description.name %></td>
        <td><%= link_to admin_description.text, admin_description %></td>
        <td><%= link_to 'Edit', edit_admin_description_path(admin_description) %></td>
        <td><%= link_to 'Destroy', admin_description, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Description', new_admin_description_path %>

app/views/admin/descriptions/new.html.erb
<h1>New admin_description</h1>

<%= form_for @admin_description, html: { class: "form-horizontal", role: "form" } do |f| %>
  <% if @admin_description.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_description.errors.count, "error") %> prohibited this admin_description from being saved:</h2>

      <ul>
      <% @admin_description.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :text, class: "col-sm-2 control-label"  %>
    <div class="col-sm-10">
      <%= f.text_area :text, class: 'form-control', rows: 25 %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit 'Save', class: "btn btn-primary" %>
    </div>
  </div>
<% end %>


<%= link_to 'Back', admin_descriptions_path %>

app/views/admin/descriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @admin_description.name %>
</p>

<p>
  <strong>Text:</strong>
  <%= dat_markdown(@admin_description.text) %>
</p>

<%= link_to 'Edit', edit_admin_description_path(@admin_description) %> |
<%= link_to 'Back', admin_descriptions_path %>