config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :descriptions
    resources :images
    resources :projects do
      member do
        get :edit_multiple_images
        put :update_multiple_images
        get :edit_multiple_descriptions
        put :update_multiple_descriptions
      end
    end
  end

  devise_for :users

  resources :images
  resources :projects, path: ''

end

app/models/admin/image.rb
class Admin::Image < Image
end

app/models/image.rb
class Image < ActiveRecord::Base

  has_many :assets, foreign_key: 'asset_id'
  has_many :projects, through: :assets

  validates :url, presence: true

  def square_75x75 #_s
    url.gsub("_s.jpg","") + "_s.jpg"
  end

  def square_75x100 #_t
    url.gsub("_s.jpg","") + "_t.jpg"
  end

  def square_150x150 #_q
    url.gsub("_s.jpg","") + "_q.jpg"
  end

  def small_240 #_m
    url.gsub("_s.jpg","") + "_m.jpg"
  end

  def small_320 #_n
    url.gsub("_s.jpg","") + "_n.jpg"
  end

  # def medium_500 #
    # does not have size
  # end

  def medium_640 #_z
    url.gsub("_s.jpg","") + "_z.jpg"
  end

  def medium_800 #_c
    url.gsub("_s.jpg","") + "_c.jpg"
  end

  def large_1024 #_b
    url.gsub("_s.jpg","") + "_b.jpg"
  end

end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < AdminController
  before_action :set_admin_image, only: [:show, :edit, :update, :destroy]

  # GET /admin/images
  # GET /admin/images.json
  def index
    @admin_images = Admin::Image.all
  end

  # GET /admin/images/1
  # GET /admin/images/1.json
  def show
  end

  # GET /admin/images/new
  def new
    @admin_image = Admin::Image.new
  end

  # GET /admin/images/1/edit
  def edit
  end

  # POST /admin/images
  # POST /admin/images.json
  def create
    @admin_image = Admin::Image.new(admin_image_params)

    respond_to do |format|
      if @admin_image.save
        format.html { redirect_to @admin_image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @admin_image }
      else
        format.html { render :new }
        format.json { render json: @admin_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/images/1
  # PATCH/PUT /admin/images/1.json
  def update
    respond_to do |format|
      if @admin_image.update(admin_image_params)
        format.html { redirect_to @admin_image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_image }
      else
        format.html { render :edit }
        format.json { render json: @admin_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/images/1
  # DELETE /admin/images/1.json
  def destroy
    @admin_image.destroy
    respond_to do |format|
      format.html { redirect_to admin_images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_image
      @admin_image = Admin::Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_image_params
      params.require(:admin_image).permit(:name, :url)
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  def index
    @images = Image.all
  end

  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit( :url )
    end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/admin/images/edit.html.erb
<ol class="breadcrumb">
  <li><a href="#">Images</a></li>
  <li class="active"><%= @admin_image.name %></li>
</ol>

<h1>Editing <%= @admin_image.name %></h1>

<%= form_for @admin_image, html: { class: "form-horizontal", role: "form" } do |f| %>
  <% if @admin_image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_image.errors.count, "error") %> prohibited this admin_image from being saved:</h2>

      <ul>
      <% @admin_image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :url, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :url, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit 'Save', class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

<%= link_to 'Show', @admin_image %> |
<%= link_to 'Back', admin_images_path %>

app/views/admin/images/index.html.erb
<h2>Images</h2>

<table class="table table-striped table-hover table-condensed">
  <thead>
    <tr>
      <th>#</th>
      <th>Preview</th>
      <th>Name</th>
      <th>Url</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_images.each do |admin_image| %>
      <tr>
        <td><%= link_to admin_image.id, admin_image %></td>
        <td><%= image_tag admin_image.square_75x75 %></td>
        <td><%= admin_image.name %></td>
        <td><%= link_to admin_image.url, admin_image.medium_640, target: '_blank' %></td>
        <td><%= link_to 'Edit', edit_admin_image_path(admin_image) %></td>
        <td><%= link_to 'Destroy', admin_image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_admin_image_path %>

app/views/admin/images/new.html.erb
<h1>New admin_image</h1>

<%= form_for @admin_image, html: { class: "form-horizontal", role: "form" } do |f| %>
  <% if @admin_image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_image.errors.count, "error") %> prohibited this admin_image from being saved:</h2>

      <ul>
      <% @admin_image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :url, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :url, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit 'Save', class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

<%= link_to 'Back', admin_images_path %>

app/views/admin/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @admin_image.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= link_to @admin_image.url, @admin_image.url, taget: 'blank' %>
</p>

<%= link_to 'Edit', edit_admin_image_path(@admin_image) %> |
<%= link_to 'Back', admin_images_path %>