config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :descriptions
    resources :images
    resources :projects do
      member do
        get :edit_multiple_images
        put :update_multiple_images
        get :edit_multiple_descriptions
        put :update_multiple_descriptions
      end
    end
  end

  devise_for :users

  resources :images
  resources :projects, path: ''

end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/description.rb
class Admin::Description < Description
end

app/models/admin/image.rb
class Admin::Image < Image
end

app/models/admin/project.rb
class Admin::Project < Project

  geocoded_by :address
  after_validation :geocode

  def update_assets(arr, type)
    current_assets_ids = current_assets(type).map(&:asset_id)
    add_assets(arr - current_assets_ids, type)
    assets_to_delete = self.assets.where(asset_type: type).where.not(asset_id: arr)
    assets_to_delete.destroy_all
  end

  def current_assets(type)
    self.assets.where(asset_type: type)
  end

  def add_assets(arr, type)
    arr.each do |id|
      self.assets.create(project_id: self, asset_id: id, asset_type: type)
    end
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/asset.rb
class Asset < ActiveRecord::Base

  belongs_to :image, foreign_key: 'asset_id'
  belongs_to :description, foreign_key: 'asset_id'
  belongs_to :project

  # def self.images
  #   where(asset_type: 'image').map { |a| a.image }
  # end

  # def self.descriptions
  #   where(asset_type: 'image').map { |a| a.image }
  # end

end

app/models/description.rb
class Description < ActiveRecord::Base

  validates :text, presence: true

  has_many :assets
  has_many :projects, -> { where assets: { asset_type: 'description' } },
            through: :assets

end

app/models/image.rb
class Image < ActiveRecord::Base

  has_many :assets, foreign_key: 'asset_id'
  has_many :projects, through: :assets

  validates :url, presence: true

  def square_75x75 #_s
    url.gsub("_s.jpg","") + "_s.jpg"
  end

  def square_75x100 #_t
    url.gsub("_s.jpg","") + "_t.jpg"
  end

  def square_150x150 #_q
    url.gsub("_s.jpg","") + "_q.jpg"
  end

  def small_240 #_m
    url.gsub("_s.jpg","") + "_m.jpg"
  end

  def small_320 #_n
    url.gsub("_s.jpg","") + "_n.jpg"
  end

  # def medium_500 #
    # does not have size
  # end

  def medium_640 #_z
    url.gsub("_s.jpg","") + "_z.jpg"
  end

  def medium_800 #_c
    url.gsub("_s.jpg","") + "_c.jpg"
  end

  def large_1024 #_b
    url.gsub("_s.jpg","") + "_b.jpg"
  end

end

app/models/project.rb
class Project < ActiveRecord::Base

  validates :title, :title, :permalink, presence: true

  before_validation :set_permalink

  has_many :assets
  has_many :descriptions, -> { where assets: { asset_type: 'description' } },
            through: :assets
  has_many :images, -> { where assets: { asset_type: 'image' } },
            through: :assets
  
  belongs_to :parent, class_name: "Project", foreign_key: "project_id"
  has_many :children, class_name: "Project", foreign_key: "project_id"
  
  scope :published, -> { where(published: true) }
  scope :parents_only, -> { where(project_id: nil) }

  def image
    images.where(assets: {main: true}).take
  end

  def random_images
    images.where(assets: {main: false}).shuffle
  end

  def description
    images.where(assets: {main: true}).take
  end

  def to_param
    permalink
  end

  def set_permalink
    self.permalink = title.parameterize
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  before_action :authenticate_user!

  layout "admin"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_filter :load_projects

  protect_from_forgery with: :exception

  def load_projects
    @projects = Project.published
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @projects = Project.all
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  def index
    @images = Image.all
  end

  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit( :url )
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :load_project, :load_hash_for_google_maps, only: :show

  def index
    redirect_to action: :show, id: 'recent-projects'
  end

  def show
    
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :permalink, :sequence)
    end

    def load_project
      @project = Project.find_by_permalink(params[:id])
    end

    def load_hash_for_google_maps
      if @project.children.present?
        @hash = Gmaps4rails.build_markers(@project.children) do |child, marker|
          marker.lat child.latitude
          marker.lng child.longitude
        end
      else
        @hash = Gmaps4rails.build_markers([@project]) do |project, marker|
          marker.lat project.latitude
          marker.lng project.longitude
        end
      end
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def dat_markdown(text)
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML,
        :autolink => true, :space_after_headers => true, :no_intra_emphasis => true)
    markdown.render(text).html_safe
  end

  def logo(size="normal")
    image_tag "", class: size
  end

  def contact_number
    "773.671.8833"
  end

  def full_address
    "<h2>Administration</h2>
    <h3>Constructions Boréal de l’Estrie</h3>
    <h4>
      1400 Émile-Zola<br />
      Sherbrooke (QC) J1L 0G8
    </h4>
    <h3>#{contact_number}</h3>".html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/_aside.html.erb
<aside class="col-sm-0 col-md-3 sidebar">

  <div class="logo visible-xs-block visible-sm-block">
    <h1><p class="text-center">ISS Construction &&nbsp;Design</p></h1>
  </div>

  <div class="logo visible-md-block visible-lg-block">
    <h1><p><%= link_to "ISS Construction &&nbsp;Design".html_safe, projects_path %></p></h1>
  </div>

  <div class="contact_number visible-xs-block visible-sm-block">
    <h2><p class="text-center"><%= contact_number %></p></h2>
  </div>

  <nav class="navbar" role="navigation">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="main-menu">
        <% @projects.parents_only.each do |p| %>
          <li class="menu-item <%= 'selected' if (@project == p) %>">
            <%= link_to p, class: 'first-level' do %>
              <%= p.title %>
              &nbsp;
              <%= content_tag(:i, '', class:"fa fa-caret-down") if p.children.present? %>
            <% end %>
            <% if p.children.present? %>
              <ul class="sub-menu">
                <% p.children.each do |ch| %>
                  <li class="menu-item <%= 'selected' if @project == ch %>">
                    <%= link_to ch.title, ch, class: 'second-level' %>
                  </li>
                <% end %>
              </ul> 
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>

  <div class="contact_number visible-md-block visible-lg-block">
    <h2><p><%= contact_number %></p></h2>
  </div>

  <div class="socialmedias visible-md-block visible-lg-block">
    <i class="fa fa-facebook-square"></i>
    <i class="fa fa-linkedin-square"></i>
  </div>

</aside>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <ul class="nav nav-tabs" role="tablist">
          <li class=<%= 'active' if controller.controller_name == 'projects' %> ><%= link_to 'Projects', admin_projects_path %></li>
          <li class=<%= 'active' if controller.controller_name == 'images' %> ><%= link_to 'Images', admin_images_path %></li>
          <li class=<%= 'active' if controller.controller_name == 'descriptions' %> ><%= link_to 'Descriptions', admin_descriptions_path %></li>
        </ul>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-12">
        <%= yield %>
      </div>
    </div>
  </div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>ISS Construction & Design</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container-fluid">
    <div class="row">

    <%= render "layouts/aside" %>

      <div class="col-sm-12 col-md-9 main">

        <%= yield %>

      </div>
    </div>
  </div>
  <%= yield :javascripts %>
</body>
</html>